# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.3
loom_version=1.13-SNAPSHOT
cloth_config_version=19.0.147
mod_menu_version=15.0.1

# Mod Properties
mod_version=1.1.0
maven_group=kunga.rpgcameraandcontrols
archives_base_name=rpg-camera-and-controls

# Dependencies
fabric_version=0.136.0+1.21.8